language: java
sudo: false

after_success:
  - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vandersozc-github -Dsonar.login=691e13b9f90d41395897736e5d467145479b8229 -Dsonar.branch=master"

install:
  - "mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

jdk:
 - oraclejdk8

cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'

notifications:
  email:
    - vando.zc@gmail.com